spring.application.name=tata-pizzeria
server.port=5322
server.servlet.context-path=/tatapizzeria
spring.datasource.url=jdbc:mysql://localhost:3306/bd_tata_pizzeria
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver