spring.application.name=tata-pizzeria

server.port=5322
server.servlet.context-path=/tatapizzeria

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.profiles.active=aws